BEMINE-UMC/Server

src/controllers/user.controller.js
src/dtos/user.dto.js
src/errors/user.error.js
src/index.js
src/repositories/user.repository.js
src/services/user.service.js

[✨FEAT]연혁 불러오기 기능 추가

---

src/controllers/post.controller.js
src/controllers/template-view.controller.js
src/controllers/template.controller.js
src/dtos/template.dto.js
src/errors/template.error.js
src/index.js
src/repositories/template.repository.js
src/services/template.service.js

Docs/#22 swagger 추가 차차

---

src/controllers/post.controller.js
src/controllers/template.controller.js
src/controllers/user.controller.js
src/index.js

[📝DOCS] #21 Swagger 추가

---

prisma/schema.prisma
src/controllers/popular.template.controller.js
src/dtos/popular.template.dto.js
src/index.js
src/repositories/popular.template.repository.js
src/services/popular.template.service.js

#18-popular-template

---

src/controllers/portfolio.post.controller.js
src/index.js

게시글 상세보기 
게시글 작성
게시글 수정
게시글 삭제 
에 대한 스웨거 작성

#31 swagger api

---

src/controllers/post.controller.js
src/controllers/template.controller.js
src/controllers/user.controller.js

[📝 docs] swagger 태그 수정

---

prisma/schema.prisma
src/controllers/post.controller.js
src/dtos/post.dto.js
src/error.js
src/errors/post.error.js
src/index.js
src/repositories/post.repository.js
src/services/post.service.js

사용자 토큰 발행되면 API 엔드포인트 변경될 것 같습니다. 
좋아요, 스크랩 삭제 API 따로 만들 예정.

[feat] 게시물 스크랩 누르기 API

---

src/errors/template.error.js

docs/template.error.js 에러코드 변경(차차)

---

src/controllers/post.controller.js
src/dtos/post.dto.js
src/errors/post.error.js
src/repositories/post.repository.js
src/services/post.service.js

[Feat] 스크랩한 게시물 목록 조회

---

src/controllers/template.controller.js
src/dtos/template.dto.js
src/errors/template.error.js
src/index.js
src/repositories/template.repository.js
src/services/template.service.js

##내용
템플릿 삭제 API 개발 완료
API endpoint 수정함 (delete -> patch)
- soft delete하기 위한 변경 사항

[feat] 템플릿 삭제 API 개발

---

src/controllers/post.controller.js
src/dtos/template.dto.js
src/services/post.service.js
src/services/template.service.js

- 최근본 게시물 조회 #50  오류 핸들링 수정, 스웨거 태그 기능으로 수정
- 스크랩한 게시물 조회 #54  오류 핸들링 수정, 스웨거 태그 기능으로 수정

re i #50 #54

---

prisma/schema.prisma
src/controllers/post.controller.js
src/controllers/user.controller.js
src/dtos/post.dto.js
src/dtos/user.dto.js
src/index.js

api 수정 및 스웨거 수정
- #16 
- #50 
- #54 
- #58 
스웨거 모든 API에 security 적용 -> 자물쇠 클릭해서 토큰 인증 기능
추가사항
- 스웨거 속성으로 #swagger.security = [] 이거 넣으면 security 적용안할수있음

i - #16 #50 #54 #58

---

package-lock.json
package.json
src/controllers/auth.controller.js
src/controllers/post.controller.js

회원가입 API
로그인 API
Access Token 재발급 API
다른 사용자의 게시글 조회 API
스웨거 코드 변경된 양식에 맞게 추가

Docs/#81-기존 API 스웨거 추가

---

src/controllers/post.controller.js
src/controllers/template.controller.js
src/errors/post.error.js
src/index.js

- controller에 스웨거에 헤더 추가, 태그 수정
- index.js파일에 미들웨어 추가
- post.error.js 에러 주석 달기

Refactor: 옌찌 담당 API Swagger, 헤더 추가

---

.github/workflows/deploy-main.yml
src/controllers/post.controller.js
src/controllers/template.controller.js
src/errors/post.error.js
src/index.js
src/repositories/post.repository.js
src/services/post.service.js
src/services/template.service.js

Develop -> Main 배포

---

src/services/post.service.js

저 딱히 뭐 없어서 에러 변수 잘못 들어간 것만 수정했습니다ㅏ.

bug: 충돌 해결

---

src/controllers/post.controller.js
src/errors/post.error.js
src/index.js
src/repositories/post.repository.js
src/services/post.service.js

[bug] 수정/삭제 충돌 해결

---

src/controllers/post.controller.js
src/services/post.service.js

[bug] 충돌해결

---

src/repositories/post.repository.js
src/services/post.service.js

게시글 상세조회에 로직 추가
별도로 API 분리 XXX

[refactor] 최근본 게시물 데이터 추가 기능

---

src/controllers/post.controller.js
src/controllers/template.controller.js
src/dtos/post.dto.js
src/dtos/template.dto.js
src/errors/template.error.js
src/index.js
src/repositories/post.repository.js
src/repositories/template.repository.js
src/services/template.service.js

- 에러로 나타냈던 부분 대신 status 변경으로 바꿈
- 스웨거도 편집
- 중간에 디벨로 한변 pull 받아서 반영

FEAT template, post 좋아요 스크랩 삭제 구현

---

middleware.js
prisma/schema.prisma
src/controllers/template.controller.js
src/dtos/template.dto.js
src/errors/template.error.js
src/index.js
src/repositories/template.repository.js
src/services/template.service.js

- 템플릿 생성 구현
- 템플릿 수정 구현
- API 2개로 만듬
- 프리즈마에 템플릿 카테고리 추가
- 프리즈마 노션 반영 X => 토요일(1/25) 회의 후 반영 예정

[Feat] 템플릿 생성/수정 #138

---

src/controllers/auth.controller.js
src/controllers/post.controller.js
src/dtos/post.dto.js
src/index.js
src/repositories/post.repository.js
src/services/post.service.js

feat:#44-좋아요 누른 게시물 조회 api

---

src/controllers/post.controller.js
src/errors/template.error.js
src/services/template.service.js

[bug] import 중복 및 post.controller -> 게시글 삭제 api 스웨거 수정

[bug] import 중복 및 swagger수정

---

src/controllers/post.controller.js
src/repositories/post.repository.js
src/services/post.service.js

- develop 풀 받아서 복붙 햇어요
- 코드 사라진거 있는지 한번 확인 부탁드려요ㅠㅠ
- 로컬 스웨거에서는 정상작동 됨

feat: 사용자 작성 게시물 조회 api

---

src/controllers/post.controller.js
src/controllers/template.controller.js
src/dtos/template.dto.js
src/errors/template.error.js
src/index.js
src/repositories/post.repository.js
src/repositories/template.repository.js
src/services/post.service.js
src/services/template.service.js

수정을 많이해서,, 지워진 부분 없는지 꼭 확인 부탁드려요..!!
템플릿 관련 api 수정
- template_category 고려해서 수정
- 로직 수정 (ex: 생성되지 않은 템플릿도 템플릿 올리는 화면에 보이도록 하기)
- 에러 핸들링 수정
- 등등.. (ex: 스웨거 수정)
SQL 수정
- 템플릿, 게시물 테이블의 status 값 관련 수정
- 템플릿 테이블의 shared_status 값 관련 수정

[Refactor] 템플릿 관련 api 수정 및 sql문 수정

---

src/controllers/auth.controller.js
src/dtos/auth.dto.js
src/errors/auth.error.js
src/index.js
src/repositories/auth.repository.js
src/services/auth.service.js

feat:#132-비밀번호 재설정 api

---

src/controllers/auth.controller.js
src/controllers/user.controller.js
src/dtos/auth.dto.js
src/dtos/user.dto.js
src/errors/auth.error.js
src/errors/user.error.js
src/index.js
src/repositories/auth.repository.js
src/repositories/user.repository.js
src/services/auth.service.js
src/services/user.service.js

- user에서 auth로 변경
- 사용자 이메일 찾기 api 구현
- 스웨거도 수정 완료!

feat: 사용자 이메일 찾기 api 구현

---

src/index.js

[refactor] 이미지 업로드 api ignore

---

src/controllers/user.controller.js
src/dtos/user.dto.js
src/errors/user.error.js
src/index.js
src/repositories/user.repository.js
src/services/user.service.js

[feature] 연혁수정 API 

---

src/controllers/auth.controller.js
src/repositories/auth.repository.js
src/repositories/post.repository.js

담당 api SQL 쿼리 최적화
----> 모든 함수 conn.release 추가
----> SQL 쿼리 중복되는 부분 하나로 줄임

refactor/#161-sql 쿼리 최적화

---

src/controllers/user.controller.js
src/dtos/user.dto.js
src/repositories/user.repository.js

[refactor] 연혁 조회 수정

---

prisma/schema.prisma
src/controllers/template.controller.js
src/dtos/template.dto.js
src/repositories/template.repository.js

템플릿 인증뱃지 추가를 위한 수정 사항입니다.
- surveyCount까지 DTO로 프론트에 보내도록 함

refactor: (템플릿 인증뱃지를 위한) 설문 완료 수 전송

---

prisma/schema.prisma
src/controllers/user.controller.js
src/dtos/user.dto.js
src/index.js
src/repositories/user.repository.js
src/services/user.service.js

프리즈마 수정
- user테이블 자기소개 추가
- 설문 부분 수정
사용자 정보 조회 기능 추가

:sparkles: [Feat] 마이페이지 사용자 정보 조회

---

prisma/schema.prisma
src/controllers/user.controller.js
src/dtos/user.dto.js
src/repositories/user.repository.js
src/services/user.service.js

♻️ [Refactor] 연혁 생성

---

src/controllers/user.controller.js
src/dtos/user.dto.js
src/repositories/user.repository.js
src/services/user.service.js

연혁수정/자기소개 수정

---

prisma/schema.prisma
src/controllers/template.controller.js
src/dtos/template.dto.js
src/index.js
src/repositories/template.repository.js
src/services/template.service.js

- develop 브랜치에 설문api pr을 안햇나봐요..?ㅠㅠ
- post로 request body 사용
- 한번 develop 변경사항 머지 상태입니다.
- 스웨거 수정 완료 content -> 유용성

feat: create survey

---

src/dtos/user.dto.js
src/repositories/user.repository.js

Develop -> main

---

src/dtos/template.dto.js
src/repositories/template.repository.js

:recycle: [refactor] 템플릿 생성 status 추가

---

src/controllers/auth.controller.js
src/dtos/auth.dto.js
src/errors/auth.error.js
src/index.js
src/repositories/auth.repository.js
src/services/auth.service.js

feat/#197-닉네임 중복 검사 API

---

src/services/post.service.js

[refactor] 게시글 작성 수정

---

src/dtos/post.dto.js
src/repositories/post.repository.js
src/services/post.service.js

refactor: 작성 post에 사용자 이름 추가

---

src/dtos/post.dto.js
src/repositories/post.repository.js

[refactor] 사용자 작성 post에 이름 추가 in 검색 게시물..

---

src/dtos/post.dto.js
src/repositories/post.repository.js
src/services/post.service.js

:recycle: [re] userId 같이 넘겨주기 완료

---

src/controllers/post.controller.js
src/controllers/user.controller.js
src/dtos/user.dto.js
src/index.js
src/repositories/user.repository.js
src/services/user.service.js

자기소개 수정기능 추가, 최본게 & 스크립트 조회 스웨거 수정

✨ feat: 자기소개 수정기능 추가, 최본게 & 스크립트 조회 스웨거 수정

---

src/services/auth.service.js

[refactor]/accessToken 시간 연장

---

src/controllers/template.controller.js
src/dtos/template.dto.js
src/repositories/template.repository.js

[refactor] 인기템플릿 file_pdf , file_ppt 속성추가

[refactor] 인기템플릿 file_pdf , file_ppt 속성추가
